server:
  port: 8092

#Admin configuration
info:
  name: @app.id@
  description: @app.id@
  version: @pom.version@
  stage: local


spring:
  application:
    id: @app.id@
    name: @app.id@
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${datasource.url}
#    username: ${datasource.username}
#    password: ${datasource.password}
#    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:config/db/db.changelog-master.xml
  profiles.active: dev
  boot:
    admin:
      client:
        url: ${boot.admin.client.url}
        username: ${boot.admin.client.username}
        password: ${boot.admin.client.password}
        instance:
          metadata:
            enable-oauth2: true



easyms:
  secured:
    azuread :
      rolesToRoles:
        SWAGGER:
          - ADMIN_CLIENT
          - SUPER_ADMIN_CLIENT
      rolesToAuthorities:
        ADMIN_CLIENT:
          - PERM_MODIFY_CLIENT
          - PERM_READ_CLIENT
        SUPER_ADMIN_CLIENT:
          - PERM_MODIFY_CLIENT
          - PERM_READ_CLIENT
          - PERM_DELETE_CLIENT
  azure:
    internalToken:
      enabled: true
#      pubKeyPath: "classpath:jwtbearer-test.pub"
      pubKeyValue: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsMQpRL3fm1I80BgrUZxX
              LlVuJoaI24eur9qWGnxsfjRwtoomQKjZEfbz9NBGURCTejWS4nRrIXF3YPdz9JU8
              3HpFMOpDtrcGvMR8IIRpiqq9rHlllnI0FIX55/o8N1Er4bYMF8s7hwJZ2/lybsWs
              VrAOU76Pz1vUq5/iD8ildZ37voSEUeCUXJOQw5dGYuZ92D1fcxyhjJYnknH9GkHS
              SwKd1KU6Kl9w4gBOrHgMbnQxypUsYV3fF0KuMMV2ZcLSJRvWMtObl1sBzv3iOhib
              N0tnWf/CRkT6ZLTcu44S9WtFvHf92vtfKI201c3X5fhK12BdOdlF6OU3l2oHoPeQ
              wwIDAQAB
              -----END PUBLIC KEY-----
      issuer: "https://c2id.com"


  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
  security:
    actuator:
      password: easymsActuatorPass!


management.endpoints.web.exposure.include: "*"

---
spring:
  profiles: sample

liquibase.contexts: data


---
spring:
  profiles: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:sdkdb;DB_CLOSE_DELAY=-1
    username: sdk
    password: secret
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2-console

---
spring:
  profiles: test
  jpa:
    hibernate.ddl-auto: none
  h2.console.enabled: false

spring.profiles.include:
  - h2

liquibase.contexts: testData

---
spring:
  profiles: azure-vault

azure:
  keyvault:
    enabled: false
    uri: https://yourvault.vault.azure.net/
    client-id: yourvault-prinicpal
    tenant-id: yourvault-tenant
    client-key: yourvault-client-key
    token-acquire-timeout-seconds: 60
    refresh-interval: 1800000
