apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: k8s-demo
        image: samarbelhadj/config-server:1.0
        ports:
        - name: server-port
          containerPort: 2001
          
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30303
    targetPort: 2001
    protocol: TCP
    name: http
  selector:
    app: server





