version: "3.8"
services:
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: veterinary_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: veterinary_db
    volumes:
      - ../init-sql/init-sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  server:
    container_name: server
    image:  config-server:1.0
    volumes:
      - ../.m2:/root/.m2
    healthcheck:
      test: "curl -f http://localhost:2001/actuator/health"
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "2001:2001"

  app:
    container_name: app
    depends_on:
      server:
          condition: service_healthy
      db:
        condition: service_started
    image: veterinary-ms:1.0
    ports:
      - "8092:8092"
    volumes:
      - ../.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/veterinary_db
      - CONFIG_SERVER_HOST=server
      - SPRING_CLOUD_CONFIG=http://server:2001
    stdin_open: true
    tty: true
  front:
    container_name: angular
    image: vet-front:1.0
    restart: always
    depends_on:
      - app
    ports:
      - '4200:80'
