
FROM maven:3.8.1-openjdk-11-slim

COPY target/veterinary-config-server-1.0.7-SNAPSHOT.jar veterinary-config-server-1.0.7-SNAPSHOT.jar


CMD ["java", "-jar", "veterinary-config-server-1.0.7-SNAPSHOT.jar"]