#Admin configuration
info:
  name: veterinary-config-server
  description: veterinary-config-server
  version: 1.0.7-SNAPSHOT
  stage: local

spring:
  application:
    id: veterinary-config-server
    name: veterinary-config-server
  boot:
    admin:
      client:
        url: http://localhost:2003
        username: admin
        password: admin

easyms:
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
      host: "localhost"
      port: 5000
      queue-size: 512